name: Deploy StoryBook

on:
  push:
    branches: [ feature/mint/test-deploy ]

jobs:
  upload:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Setting env
        run: |
          echo "BUILD_NUMBER=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew --no-daemon :app:yds-ui-tester:assembleRelease
      - name: Upload to Slack
        run: curl -F file=@"app/yds-ui-tester/build/outputs/apk/release/YDS-StoryBook_${GITHUB_RUN_NUMBER}-release.apk" -F "initial_comment=YDS StoryBook" -F "channels=${{ secrets.SLACK_CHANNEL_ID }}" -H "Authorization:Bearer ${{ secrets.SLACK_WORKSPACE_TOKEN }}" https://slack.com/api/files.upload